services:

  db:
    container_name: postgres_container
    image: postgres:16-alpine
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - my-network

  af:
    container_name: airflow_container
    build: .
    ports:
      - "8000:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://db_user:db_password@db:5432/db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-network
    command: >
      bash -c "airflow db migrate && airflow standalone"

networks:
  my-network:
    driver: bridge
